import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayout from "./MainLayout";
import { SessionProvider } from "./userSession/session";


export const metadata: Metadata = {
  title: "Business",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={``}
      >
        <SessionProvider>
          <MainLayout>
          {children}
          </MainLayout>
        </SessionProvider>
        
      </body>
    </html>
  );
}
